spring:
  ai:
    alibaba:
      toolcalling:
        baidu:
          translate:
            enabled: true
            app-id: ${BAIDU_TRANSLATE_APP_ID}
            secret-key: ${BAIDU_TRANSLATE_SECRET_KEY}
          map:
            apiKey: ${BAIDU_MAP_API_KEY}

        time:
          enabled: true

        weather:
          enabled: true
          api-key: ${WEATHER_API_KEY}

        githubtoolkit:
          enabled: true
          token: ${GITHUB_TOKEN}
          owner: ${GITHUB_OWNER}
          repository: ${GITHUB_REPOSITORY}

    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
