server:
  port: 8080

spring:
  application:
    name: elasticsearch-example

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: spring_ai_alibaba_index
        similarity: cosine
        dimensions: 1536

  elasticsearch:
    uris: https://127.0.0.1:9200
    username: elastic
    password: yingzi
