server:
  port: 10001

spring:
  application:
    name: spring-ai-alibaba-deepseek-chat-client-example

  ai:
    openai:
      api-key:
        ${AI_OPENAI_API_KEY}
      base-url: ${AI_OPENAI_BASE_URL}
      chat:
        options:
          model: ${AI_OPENAI_CHAT_MODEL}
      embedding:
        enabled: false