mcpServers:
  weather:
    command: java
    args:
      - "-Dspring.ai.mcp.server.stdio=true"
      - "-Dspring.main.web-application-type=none"
      - "-Dlogging.pattern.console="
      - "-jar"
      - "mcp-libs/weather.jar"
    env: {}
