spring:
  application:
    name: spring-ai-alibaba-dynamic-mcp-server-example
  ai:
    mcp:
      server:
        name: dynamic-mcp-server
        version: 1.0.0
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max-latest

    alibaba:
      mcp:
        nacos:
          enabled: true
          server-addr: localhost:8848
          username: nacos
          password:
          dynamic:
            enabled: true
            service-namespace: public
            service-group: DEFAULT_GROUP
            service-names: echo-server

server:
  port: 8090
